#!/bin/bash

# ============================================
# RHT Fault-Tolerant Deployment Configuration
# ============================================
# CloudLab APT deployment - each node is independent (no shared filesystem)

# Your CloudLab username
USERNAME="Alexis"

# CloudLab APT node list (from your nodes)
# Updated 2026-04-04 with new allocation
CLOUDLAB_NODES=(
    "apt144.apt.emulab.net"
    "apt152.apt.emulab.net"
    "apt153.apt.emulab.net"
    "apt148.apt.emulab.net"
    "apt157.apt.emulab.net"
    "apt142.apt.emulab.net"
    "apt158.apt.emulab.net"
    "apt149.apt.emulab.net"
    "apt139.apt.emulab.net"
)

# No suffix needed - using full hostnames
CLOUDLAB_SUFFIX=""

# SSH key for passwordless access (id_cloudlab_rh key you created)
SSH_KEY="$HOME/.ssh/id_cloudlab_rh"
SSH_OPTS=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null)
if [ -f "$SSH_KEY" ]; then
    SSH_OPTS+=(-i "$SSH_KEY")
fi

# Base ports for RHT nodes
BASE_CLIENT_PORT=8000  # Client connections
BASE_SERVER_PORT=8001  # Server-to-server connections (monitoring/coordinator)

# Remote directory on CloudLab nodes (user home directory)
REMOTE_DIR="/users/${USERNAME}/rht_fault_recover"

# Local directory
LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Selected servers file (generated by smart_deploy.sh)
SELECTED_SERVERS_FILE="${LOCAL_DIR}/.selected_servers"

# Default cluster parameters
DEFAULT_REPLICATION_FACTOR=3
DEFAULT_VNODES_NUMBER=256  # Virtual nodes per physical node for consistent hashing
DEFAULT_NUMBER_OF_KEYS=10000
DEFAULT_CLIENT_EVENT_QUEUE_SIZE=10000
DEFAULT_MONITORING_EVENT_QUEUE_SIZE=1000
DEFAULT_WORKER_POOL_SIZE=14

# Deployment settings
RSYNC_EXCLUDE="--exclude='build/' --exclude='logs/' --exclude='results/' --exclude='collected_results/' --exclude='.git/' --exclude='*.o' --exclude='*.a' --exclude='config/*.yaml'"

# Build command on remote server (CloudLab Ubuntu)
# Using CMake build system (supports RDMA auto-detection)
REMOTE_BUILD_CMD="cd ${REMOTE_DIR} && mkdir -p build && cd build && cmake .. && make -j\$(nproc)"

# Dependency installation (run once per node)
INSTALL_DEPS_SCRIPT="install_dependencies.sh"

# Colors for output
COLOR_RESET='\033[0m'
COLOR_GREEN='\033[0;32m'
COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_CYAN='\033[0;36m'
COLOR_MAGENTA='\033[0;35m'

# Helper functions
log_info() {
    echo -e "${COLOR_CYAN}[INFO]${COLOR_RESET} $1"
}

log_success() {
    echo -e "${COLOR_GREEN}[SUCCESS]${COLOR_RESET} $1"
}

log_error() {
    echo -e "${COLOR_RED}[ERROR]${COLOR_RESET} $1"
}

log_warning() {
    echo -e "${COLOR_YELLOW}[WARNING]${COLOR_RESET} $1"
}

log_step() {
    echo -e "${COLOR_MAGENTA}[STEP]${COLOR_RESET} $1"
}

# Helper function to get full hostname (no suffix needed for APT nodes)
get_full_hostname() {
    local node=$1
    echo "$node"
}

# Export variables for other scripts
export USERNAME
export CLOUDLAB_NODES
export CLOUDLAB_SUFFIX
export SSH_KEY
export SSH_OPTS
export BASE_CLIENT_PORT
export BASE_SERVER_PORT
export REMOTE_DIR
export LOCAL_DIR
export DEFAULT_REPLICATION_FACTOR
export DEFAULT_VNODES_NUMBER
export DEFAULT_NUMBER_OF_KEYS
export DEFAULT_CLIENT_EVENT_QUEUE_SIZE
export DEFAULT_MONITORING_EVENT_QUEUE_SIZE
export DEFAULT_WORKER_POOL_SIZE
