#!/bin/bash

# ============================================
# Generate YAML Configuration Files
# ============================================
# Generates node-specific YAML configs based on deploy_config.sh
# and the Config class structure from config.h/config.cpp

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/deploy_config.sh"

# ============================================
# Configuration
# ============================================

NUM_PREFILL_NODES=${1:-2}
NUM_DECODE_NODES=${2:-2}

# Validate we have enough nodes
TOTAL_NODES=$((1 + NUM_PREFILL_NODES + NUM_DECODE_NODES))
if [ $TOTAL_NODES -gt ${#CLOUDLAB_NODES[@]} ]; then
    log_error "Not enough CloudLab nodes. Need $TOTAL_NODES, have ${#CLOUDLAB_NODES[@]}"
    exit 1
fi

# Assign nodes
ORCHESTRATOR_NODE="${CLOUDLAB_NODES[0]}"
PREFILL_NODES=("${CLOUDLAB_NODES[@]:1:$NUM_PREFILL_NODES}")
DECODE_NODES=("${CLOUDLAB_NODES[@]:$((1+NUM_PREFILL_NODES)):$NUM_DECODE_NODES}")

# Create configs directory
CONFIGS_DIR="${LOCAL_DIR}/configs"
mkdir -p "${CONFIGS_DIR}"

log_info "=========================================="
log_info "Generating YAML Configuration Files"
log_info "=========================================="
echo ""
log_info "Orchestrator: ${ORCHESTRATOR_NODE}"
log_info "Prefill nodes (${NUM_PREFILL_NODES}): ${PREFILL_NODES[@]}"
log_info "Decode nodes (${NUM_DECODE_NODES}): ${DECODE_NODES[@]}"
echo ""

# ============================================
# Generate Orchestrator Config
# ============================================

log_step "Generating orchestrator config..."

ORCHESTRATOR_HOST=$(get_full_hostname "$ORCHESTRATOR_NODE")

cat > "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
# Orchestrator Configuration
# Auto-generated by generate_configs.sh

host: "${ORCHESTRATOR_HOST}"
client_socket_port: ${ORCHESTRATOR_PORT}
server_socket_port: ${ORCHESTRATOR_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_PORT}

# Cluster settings
replication_factor: 3
number_of_keys_hashtable: 10000
size_local_buffer: 1024
event_queue_size: 1000
worker_pool_size: 4
vnodes_number: 1

num_layers: 32

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU:-true}

# Orchestrator specific settings
orchestrator:
  expected_decode_nodes: ${NUM_DECODE_NODES}
  expected_prefill_nodes: ${NUM_PREFILL_NODES}

# Node configuration
node:
  role: "orchestrator"

# Prefill nodes list
prefill_nodes:
EOF

# Add prefill nodes
for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

# Add decode nodes list
cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

# Add peers list (all nodes except orchestrator)
cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF

# All peer nodes
peers:
EOF

for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

log_success "Generated orchestrator.yaml"

# ============================================
# Generate Prefill Node Configs
# ============================================

log_step "Generating prefill node configs..."

for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    NODE_ID="prefill-$(printf '%02d' $i)"
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))
    VLLM_PORT=$((VLLM_PREFILL_BASE_PORT + i))

cat > "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
# Prefill Node Configuration - ${NODE_ID}
# Auto-generated by generate_configs.sh

host: "${HOST}"
client_socket_port: ${CLIENT_PORT}
server_socket_port: ${SERVER_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_PORT}

# vLLM configuration
vllm_port: ${VLLM_PORT}
model_name: "${MODEL_NAME}"

# Cluster settings
replication_factor: 3
number_of_keys_hashtable: 10000
size_local_buffer: 1024
event_queue_size: 1000
worker_pool_size: 4
vnodes_number: 1

num_layers: 32

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU:-true}

# Node configuration
node:
  role: "prefill"

  # InfiniBand / RDMA fabric
  ib_port: 1              # Physical IB port (usually 1)
  gid_index: 0            # 0=IB, 3=RoCEv2
  mtu: 4096               # Path MTU: 512/1024/2048/4096
  sl: 0                   # Service Level

  # QP Tuning
  qp_max_send_wr: 64
  qp_max_recv_wr: 64
  qp_max_inline_data: 64
  max_rd_atomic: 16
  min_rnr_timer: 12       # ~0.64 ms
  timeout: 14             # local ACK timeout (~67 ms)
  retry_cnt: 7
  rnr_retry: 7            # 7 = infinite

  # Completion Queue
  cq_depth: 128

  # GPU selection
  enable_peer_access: true    # Enable P2P between GPUs
  require_same_numa: false    # Require GPU and HCA on same NUMA node

# Memory Configuration
memory:
  kv_buffer_mb: 16384           # Total GPU memory buffer (16 GB)
  chunk_size_mb: 64             # Size of each chunk (64-128 MB recommended)
  num_kv_chunks: 32             # Number of chunks per request
  mr_relaxed_ordering: true     # Enable PCIe relaxed ordering for better BW
  max_concurrent_requests: 8    # Max simultaneous KV transfers

# Prefill nodes list
prefill_nodes:
EOF

    # Add all prefill nodes (for peer communication)
    for j in "${!PREFILL_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${PREFILL_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add decode nodes list
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

    for j in "${!DECODE_NODES[@]}"; do
        PEER_NODE="${DECODE_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add all peers
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# All peer nodes (excluding self)
peers:
EOF

    # Add other prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${PREFILL_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add all decode nodes
    for j in "${!DECODE_NODES[@]}"; do
        PEER_NODE="${DECODE_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    log_success "Generated ${NODE_ID}.yaml"
done

# ============================================
# Generate Decode Node Configs
# ============================================

log_step "Generating decode node configs..."

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    NODE_ID="decode-$(printf '%02d' $i)"
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))
    VLLM_PORT=$((VLLM_DECODE_BASE_PORT + i))

cat > "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
# Decode Node Configuration - ${NODE_ID}
# Auto-generated by generate_configs.sh

host: "${HOST}"
client_socket_port: ${CLIENT_PORT}
server_socket_port: ${SERVER_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_PORT}

# vLLM configuration
vllm_port: ${VLLM_PORT}
model_name: "${MODEL_NAME}"

# Cluster settings
replication_factor: 3
number_of_keys_hashtable: 10000
size_local_buffer: 1024
event_queue_size: 1000
worker_pool_size: 4
vnodes_number: 1

num_layers: 32

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU:-true}

# Node configuration
node:
  role: "decode"

  # InfiniBand / RDMA fabric
  ib_port: 1              # Physical IB port (usually 1)
  gid_index: 0            # 0=IB, 3=RoCEv2
  mtu: 4096               # Path MTU: 512/1024/2048/4096
  sl: 0                   # Service Level

  # QP Tuning
  qp_max_send_wr: 64
  qp_max_recv_wr: 64
  qp_max_inline_data: 64
  max_rd_atomic: 16
  min_rnr_timer: 12       # ~0.64 ms
  timeout: 14             # local ACK timeout (~67 ms)
  retry_cnt: 7
  rnr_retry: 7            # 7 = infinite

  # Completion Queue
  cq_depth: 128

  # GPU selection
  enable_peer_access: true    # Enable P2P between GPUs
  require_same_numa: false    # Require GPU and HCA on same NUMA node

# Memory Configuration
memory:
  kv_buffer_mb: 16384           # Total GPU memory buffer (16 GB)
  chunk_size_mb: 64             # Size of each chunk (64-128 MB recommended)
  num_kv_chunks: 32             # Number of chunks per request
  mr_relaxed_ordering: true     # Enable PCIe relaxed ordering for better BW
  max_concurrent_requests: 8    # Max simultaneous KV transfers

# Prefill nodes list
prefill_nodes:
EOF

    # Add all prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        PEER_NODE="${PREFILL_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add decode nodes list
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

    for j in "${!DECODE_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${DECODE_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add all peers
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# All peer nodes (excluding self)
peers:
EOF

    # Add all prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        PEER_NODE="${PREFILL_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add other decode nodes
    for j in "${!DECODE_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${DECODE_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    log_success "Generated ${NODE_ID}.yaml"
done

# ============================================
# Summary
# ============================================

echo ""
log_success "=========================================="
log_success "Configuration Generation Complete!"
log_success "=========================================="
echo ""
log_info "Generated files in ${CONFIGS_DIR}:"
echo "  - orchestrator.yaml"
for i in "${!PREFILL_NODES[@]}"; do
    NODE_ID="prefill-$(printf '%02d' $i)"
    echo "  - ${NODE_ID}.yaml"
done
for i in "${!DECODE_NODES[@]}"; do
    NODE_ID="decode-$(printf '%02d' $i)"
    echo "  - ${NODE_ID}.yaml"
done
echo ""
log_info "Next steps:"
echo "  1. Review the generated configs: ls -la ${CONFIGS_DIR}"
echo "  2. Deploy to nodes: ./scripts/smart_deploy.sh ${TOTAL_NODES}"
echo "  3. Start the system: ./scripts/smart_run.sh ${NUM_PREFILL_NODES} ${NUM_DECODE_NODES}"
echo ""
