#!/bin/bash

# ============================================
# Generate YAML Configuration Files
# ============================================
# Generates node-specific YAML configs based on deploy_config.sh
# and the Config class structure from config.h/config.cpp

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/deploy_config.sh"

# ============================================
# Configuration
# ============================================

NUM_PREFILL_NODES=${1:-2}
NUM_DECODE_NODES=${2:-2}

# Validate we have enough nodes
TOTAL_NODES=$((1 + NUM_PREFILL_NODES + NUM_DECODE_NODES))
if [ $TOTAL_NODES -gt ${#CLOUDLAB_NODES[@]} ]; then
    log_error "Not enough CloudLab nodes. Need $TOTAL_NODES, have ${#CLOUDLAB_NODES[@]}"
    exit 1
fi

# Assign nodes
ORCHESTRATOR_NODE="${CLOUDLAB_NODES[0]}"
PREFILL_NODES=("${CLOUDLAB_NODES[@]:1:$NUM_PREFILL_NODES}")
DECODE_NODES=("${CLOUDLAB_NODES[@]:$((1+NUM_PREFILL_NODES)):$NUM_DECODE_NODES}")

# Create configs directory
CONFIGS_DIR="${LOCAL_DIR}/configs"
mkdir -p "${CONFIGS_DIR}"

log_info "=========================================="
log_info "Generating YAML Configuration Files"
log_info "=========================================="
echo ""
log_info "Orchestrator: ${ORCHESTRATOR_NODE}"
log_info "Prefill nodes (${NUM_PREFILL_NODES}): ${PREFILL_NODES[@]}"
log_info "Decode nodes (${NUM_DECODE_NODES}): ${DECODE_NODES[@]}"
echo ""

# ============================================
# Generate Orchestrator Config
# ============================================

log_step "Generating orchestrator config..."

ORCHESTRATOR_HOST=$(get_full_hostname "$ORCHESTRATOR_NODE")

cat > "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
# Orchestrator Configuration
# Auto-generated by generate_configs.sh

host: "${ORCHESTRATOR_HOST}"
client_socket_port: ${ORCHESTRATOR_PORT}
server_socket_port: ${ORCHESTRATOR_NODE_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_NODE_PORT}

# Cluster settings
replication_factor: ${REPLICATION_FACTOR}
number_of_keys_hashtable: ${NUMBER_OF_KEYS_HASHTABLE}
size_local_buffer: ${SIZE_LOCAL_BUFFER}
event_queue_size: ${EVENT_QUEUE_SIZE}
worker_pool_size: ${WORKER_POOL_SIZE}
vnodes_number: ${VNODES_NUMBER}

num_layers: ${NUM_LAYERS}

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU}

# Orchestrator specific settings
orchestrator:
  expected_decode_nodes: ${NUM_DECODE_NODES}
  expected_prefill_nodes: ${NUM_PREFILL_NODES}

# Node configuration
node:
  role: "orchestrator"

# Prefill nodes list
prefill_nodes:
EOF

# Add prefill nodes
for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

# Add decode nodes list
cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

# Add peers list (all nodes except orchestrator)
cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF

# All peer nodes
peers:
EOF

for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))

cat >> "${CONFIGS_DIR}/orchestrator.yaml" <<EOF
  - host: "${HOST}"
    client_socket_port: ${CLIENT_PORT}
    server_socket_port: ${SERVER_PORT}
EOF
done

log_success "Generated orchestrator.yaml"

# ============================================
# Generate Prefill Node Configs
# ============================================

log_step "Generating prefill node configs..."

for i in "${!PREFILL_NODES[@]}"; do
    NODE="${PREFILL_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    NODE_ID="prefill-$(printf '%02d' $i)"
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + i + 1))
    VLLM_PORT=$((VLLM_PREFILL_BASE_PORT + i))

cat > "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
# Prefill Node Configuration - ${NODE_ID}
# Auto-generated by generate_configs.sh

host: "${HOST}"
client_socket_port: ${CLIENT_PORT}
server_socket_port: ${SERVER_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_NODE_PORT}

# vLLM configuration
vllm_port: ${VLLM_PORT}
model_name: "${MODEL_NAME}"
gpu_memory_utilization: ${GPU_MEMORY_UTILIZATION}

# Cluster settings
replication_factor: ${REPLICATION_FACTOR}
number_of_keys_hashtable: ${NUMBER_OF_KEYS_HASHTABLE}
size_local_buffer: ${SIZE_LOCAL_BUFFER}
event_queue_size: ${EVENT_QUEUE_SIZE}
worker_pool_size: ${WORKER_POOL_SIZE}
vnodes_number: ${VNODES_NUMBER}

num_layers: ${NUM_LAYERS}

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU}

# Node configuration
node:
  role: "prefill"

  # InfiniBand / RDMA fabric
  ib_port: ${IB_PORT}              # Physical IB port (usually 1)
  gid_index: ${NODE_GID_INDEX}            # 0=IB, 3=RoCEv2
  mtu: ${NODE_MTU}               # Path MTU: 512/1024/2048/4096
  sl: ${NODE_SL}                   # Service Level

  # QP Tuning
  qp_max_send_wr: ${NODE_QP_MAX_SEND_WR}
  qp_max_recv_wr: ${NODE_QP_MAX_RECV_WR}
  qp_max_inline_data: ${NODE_QP_MAX_INLINE_DATA}
  max_rd_atomic: ${NODE_MAX_RD_ATOMIC}
  min_rnr_timer: ${NODE_MIN_RNR_TIMER}       # ~0.64 ms
  timeout: ${NODE_TIMEOUT}             # local ACK timeout (~67 ms)
  retry_cnt: ${NODE_RETRY_CNT}
  rnr_retry: ${NODE_RNR_RETRY}            # 7 = infinite

  # Completion Queue
  cq_depth: ${NODE_CQ_DEPTH}

  # GPU selection
  enable_peer_access: ${NODE_ENABLE_PEER_ACCESS}    # Enable P2P between GPUs
  require_same_numa: ${NODE_REQUIRE_SAME_NUMA}    # Require GPU and HCA on same NUMA node

# Memory Configuration
memory:
  kv_buffer_mb: ${MEMORY_KV_BUFFER_MB}           # Total GPU memory buffer (16 GB)
  layer_size_mb: ${MEMORY_LAYER_SIZE_MB}            # Per-layer KV cache size (128 MB default)
  chunk_size_mb: ${MEMORY_CHUNK_SIZE_MB}             # Size of each chunk (64-128 MB recommended)
  num_kv_chunks: ${MEMORY_NUM_KV_CHUNKS}             # Number of chunks per request
  mr_relaxed_ordering: ${MEMORY_MR_RELAXED_ORDERING}     # Enable PCIe relaxed ordering for better BW
  max_concurrent_requests: ${MEMORY_MAX_CONCURRENT_REQUESTS}    # Max simultaneous KV transfers

# Prefill nodes list
prefill_nodes:
EOF

    # Add all prefill nodes (for peer communication)
    for j in "${!PREFILL_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${PREFILL_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add decode nodes list
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

    for j in "${!DECODE_NODES[@]}"; do
        PEER_NODE="${DECODE_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add all peers
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# All peer nodes (excluding self)
peers:
EOF

    # Add other prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${PREFILL_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add all decode nodes
    for j in "${!DECODE_NODES[@]}"; do
        PEER_NODE="${DECODE_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    log_success "Generated ${NODE_ID}.yaml"
done

# ============================================
# Generate Decode Node Configs
# ============================================

log_step "Generating decode node configs..."

for i in "${!DECODE_NODES[@]}"; do
    NODE="${DECODE_NODES[$i]}"
    HOST=$(get_full_hostname "$NODE")
    NODE_ID="decode-$(printf '%02d' $i)"
    CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + i))
    SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + i + 1))
    VLLM_PORT=$((VLLM_DECODE_BASE_PORT + i))

cat > "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
# Decode Node Configuration - ${NODE_ID}
# Auto-generated by generate_configs.sh

host: "${HOST}"
client_socket_port: ${CLIENT_PORT}
server_socket_port: ${SERVER_PORT}

orchestrator_host: "${ORCHESTRATOR_HOST}"
orchestrator_port: ${ORCHESTRATOR_NODE_PORT}

# vLLM configuration
vllm_port: ${VLLM_PORT}
model_name: "${MODEL_NAME}"
gpu_memory_utilization: ${GPU_MEMORY_UTILIZATION}

# Cluster settings
replication_factor: ${REPLICATION_FACTOR}
number_of_keys_hashtable: ${NUMBER_OF_KEYS_HASHTABLE}
size_local_buffer: ${SIZE_LOCAL_BUFFER}
event_queue_size: ${EVENT_QUEUE_SIZE}
worker_pool_size: ${WORKER_POOL_SIZE}
vnodes_number: ${VNODES_NUMBER}

num_layers: ${NUM_LAYERS}

# Transfer backend selection
# use_gpu: true  -> GPUDirect RDMA (RDMAConnector, requires nvidia-peermem + A100-class GPU)
# use_gpu: false -> Standard RDMA via MooncakeConnector (no GPU required)
use_gpu: ${USE_GPU}

# Node configuration
node:
  role: "decode"

  # InfiniBand / RDMA fabric
  ib_port: ${IB_PORT}              # Physical IB port (usually 1)
  gid_index: ${NODE_GID_INDEX}            # 0=IB, 3=RoCEv2
  mtu: ${NODE_MTU}               # Path MTU: 512/1024/2048/4096
  sl: ${NODE_SL}                   # Service Level

  # QP Tuning
  qp_max_send_wr: ${NODE_QP_MAX_SEND_WR}
  qp_max_recv_wr: ${NODE_QP_MAX_RECV_WR}
  qp_max_inline_data: ${NODE_QP_MAX_INLINE_DATA}
  max_rd_atomic: ${NODE_MAX_RD_ATOMIC}
  min_rnr_timer: ${NODE_MIN_RNR_TIMER}       # ~0.64 ms
  timeout: ${NODE_TIMEOUT}             # local ACK timeout (~67 ms)
  retry_cnt: ${NODE_RETRY_CNT}
  rnr_retry: ${NODE_RNR_RETRY}            # 7 = infinite

  # Completion Queue
  cq_depth: ${NODE_CQ_DEPTH}

  # GPU selection
  enable_peer_access: ${NODE_ENABLE_PEER_ACCESS}    # Enable P2P between GPUs
  require_same_numa: ${NODE_REQUIRE_SAME_NUMA}    # Require GPU and HCA on same NUMA node

# Memory Configuration
memory:
  kv_buffer_mb: ${MEMORY_KV_BUFFER_MB}           # Total GPU memory buffer (16 GB)
  layer_size_mb: ${MEMORY_LAYER_SIZE_MB}            # Per-layer KV cache size (128 MB default)
  chunk_size_mb: ${MEMORY_CHUNK_SIZE_MB}             # Size of each chunk (64-128 MB recommended)
  num_kv_chunks: ${MEMORY_NUM_KV_CHUNKS}             # Number of chunks per request
  mr_relaxed_ordering: ${MEMORY_MR_RELAXED_ORDERING}     # Enable PCIe relaxed ordering for better BW
  max_concurrent_requests: ${MEMORY_MAX_CONCURRENT_REQUESTS}    # Max simultaneous KV transfers

# Prefill nodes list
prefill_nodes:
EOF

    # Add all prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        PEER_NODE="${PREFILL_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add decode nodes list
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# Decode nodes list
decode_nodes:
EOF

    for j in "${!DECODE_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${DECODE_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    # Add all peers
cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF

# All peer nodes (excluding self)
peers:
EOF

    # Add all prefill nodes
    for j in "${!PREFILL_NODES[@]}"; do
        PEER_NODE="${PREFILL_NODES[$j]}"
        PEER_HOST=$(get_full_hostname "$PEER_NODE")
        PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + j))
        PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
    done

    # Add other decode nodes
    for j in "${!DECODE_NODES[@]}"; do
        if [ $i -ne $j ]; then
            PEER_NODE="${DECODE_NODES[$j]}"
            PEER_HOST=$(get_full_hostname "$PEER_NODE")
            PEER_CLIENT_PORT=$((NODE_TCP_BASE_PORT + 100 + j))
            PEER_SERVER_PORT=$((NODE_TCP_BASE_PORT + 100 + j + 1))

cat >> "${CONFIGS_DIR}/${NODE_ID}.yaml" <<EOF
  - host: "${PEER_HOST}"
    client_socket_port: ${PEER_CLIENT_PORT}
    server_socket_port: ${PEER_SERVER_PORT}
EOF
        fi
    done

    log_success "Generated ${NODE_ID}.yaml"
done

# ============================================
# Summary
# ============================================

echo ""
log_success "=========================================="
log_success "Configuration Generation Complete!"
log_success "=========================================="
echo ""
log_info "Generated files in ${CONFIGS_DIR}:"
echo "  - orchestrator.yaml"
for i in "${!PREFILL_NODES[@]}"; do
    NODE_ID="prefill-$(printf '%02d' $i)"
    echo "  - ${NODE_ID}.yaml"
done
for i in "${!DECODE_NODES[@]}"; do
    NODE_ID="decode-$(printf '%02d' $i)"
    echo "  - ${NODE_ID}.yaml"
done
echo ""
log_info "Next steps:"
echo "  1. Review the generated configs: ls -la ${CONFIGS_DIR}"
echo "  2. Deploy to nodes: ./scripts/smart_deploy.sh ${TOTAL_NODES}"
echo "  3. Start the system: ./scripts/smart_run.sh ${NUM_PREFILL_NODES} ${NUM_DECODE_NODES}"
echo ""
